"use client";

// import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { Provider } from "react-redux";
import { store } from "./store/store";
import Navbar from "@/components/Navbar";
import { usePathname } from "next/navigation"; // Import the usePathname hook

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const pathname = usePathname(); // Get the current route
  const hideNavbarRoutes = ["/signup", "/login"]; // List of routes where the Navbar should be hidden

  return (
    <Provider store={store}>
      <html lang="en">
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased  min-h-[100vh] bg-lightGray`}
        >
          {" "}
          {!hideNavbarRoutes.includes(pathname) && <Navbar />}
          {children}
        </body>
      </html>
    </Provider>
  );
}
